// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dashboard/ads_analysis": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "提取包含品牌偏好饼图、卖点词云及视频明细的大盘数据。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard 大盘数据"
                ],
                "summary": "获取 KOL 近30天商单 AI 分析结果",
                "responses": {
                    "200": {
                        "description": "成功返回商单分析数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.AdsAnalysisDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/dashboard/overview": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "结合 Redis 缓存，毫秒级获取指定 KOL 近30天的均播、中位数以及互动率等基础大盘数据。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard 大盘数据"
                ],
                "summary": "获取 KOL 数据大盘核心概览指标",
                "responses": {
                    "200": {
                        "description": "成功返回大盘数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.KOLOverviewDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/dashboard/trend": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回前端 ECharts 能够直接渲染的 Category 和 Series 格式数据。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard 大盘数据"
                ],
                "summary": "获取 KOL 数据大盘的时间窗口趋势图(折线图)",
                "responses": {
                    "200": {
                        "description": "成功返回趋势数据",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.TrendChartDTO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.AdVideoItem": {
            "type": "object",
            "properties": {
                "brand_name": {
                    "type": "string"
                },
                "bvid": {
                    "type": "string"
                },
                "insert_time": {
                    "type": "string"
                },
                "product_name": {
                    "type": "string"
                },
                "selling_points": {
                    "description": "自动解析 ClickHouse 的 Array(String)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "model.AdsAnalysisDTO": {
            "type": "object",
            "properties": {
                "brand_distribution": {
                    "description": "品牌偏好",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BrandCount"
                    }
                },
                "mid": {
                    "type": "integer"
                },
                "recent_videos": {
                    "description": "视频列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.AdVideoItem"
                    }
                },
                "top_selling_points": {
                    "description": "核心带货卖点",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.PointCount"
                    }
                },
                "total_ads_30d": {
                    "description": "近30天商单总数",
                    "type": "integer"
                }
            }
        },
        "model.BrandCount": {
            "type": "object",
            "properties": {
                "brand_name": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                }
            }
        },
        "model.ChartSeries": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "对应 30/90/180/365 的数据数组",
                    "type": "array",
                    "items": {
                        "type": "number"
                    }
                },
                "name": {
                    "description": "图例名称 (如: \"平均播放量\")",
                    "type": "string"
                },
                "smooth": {
                    "description": "是否平滑曲线",
                    "type": "boolean"
                },
                "type": {
                    "description": "图表类型 (如: \"line\", \"bar\")",
                    "type": "string"
                }
            }
        },
        "model.KOLOverviewDTO": {
            "type": "object",
            "properties": {
                "avg_view_30d": {
                    "type": "number"
                },
                "engagement_rate": {
                    "description": "衍生计算指标",
                    "type": "number"
                },
                "median_view_30d": {
                    "type": "number"
                },
                "mid": {
                    "type": "integer"
                },
                "radar": {
                    "description": "雷达图数据挂载点",
                    "allOf": [
                        {
                            "$ref": "#/definitions/model.RadarScoreDTO"
                        }
                    ]
                },
                "stability_ratio": {
                    "description": "衍生计算指标",
                    "type": "number"
                },
                "stat_date": {
                    "type": "string"
                },
                "video_count_30d": {
                    "type": "integer"
                }
            }
        },
        "model.PointCount": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "point": {
                    "type": "string"
                }
            }
        },
        "model.RadarScoreDTO": {
            "type": "object",
            "properties": {
                "active_score": {
                    "description": "活跃度(基于发稿频率)",
                    "type": "number"
                },
                "interact_score": {
                    "description": "互动性(基于整体互动率)",
                    "type": "number"
                },
                "loyalty_score": {
                    "description": "铁粉度(基于投币率)",
                    "type": "number"
                },
                "planting_score": {
                    "description": "种草力(基于收藏率)",
                    "type": "number"
                },
                "spread_score": {
                    "description": "传播力(基于均播)",
                    "type": "number"
                },
                "stable_score": {
                    "description": "稳定性(基于中位数/均值的比值)",
                    "type": "number"
                }
            }
        },
        "model.TrendChartDTO": {
            "type": "object",
            "properties": {
                "categories": {
                    "description": "X轴坐标: [\"近30天\", \"近90天\", \"近180天\", \"近一年\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "mid": {
                    "type": "integer"
                },
                "series": {
                    "description": "Y轴数据列",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ChartSeries"
                    }
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8083",
	BasePath:         "/api/v1/monitor",
	Schemes:          []string{},
	Title:            "KOL 营销平台 - 数据监控大脑 API",
	Description:      "Data Monitor Microservice API Docs. 负责提供 KOL 核心数据大盘与 AI 洞察分析。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
