// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/internal/v1/user/ugc/callback": {
            "post": {
                "responses": {}
            }
        },
        "/api/internal/v1/user/{id}/profile": {
            "get": {
                "description": "无需 Token，供报价引擎或匹配系统通过 user_id 直接查询。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Internal"
                ],
                "summary": "内部调用：查询用户详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回用户信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "验证账号密码并返回 Opaque Token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"success\",\"data\":{...}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/auth/register": {
            "post": {
                "description": "注册红人(role:1)或品牌方(role:2)账号",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RegisterReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"success\",\"data\":{\"message\":\"注册成功，请登录\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/avatar/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "上传图片文件，自动根据当前 Token 身份更新红人或品牌方的头像。每人每 7 天只能修改一次。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "上传用户头像 (7天冷却)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "头像图片文件 (最大 5MB, 仅支持 jpg/png)",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回新的头像 URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/brand/license/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "验证登录密码后，物理删除服务器上的资质文件并清空记录。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "销毁营业执照 (仅限品牌方)",
                "parameters": [
                    {
                        "description": "密码校验参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.DeleteLicenseReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功提示",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/brand/license/upload": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "品牌方角色专属。上传营业执照图片，大小不超过 10MB。",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "上传营业执照 (仅限品牌方)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "营业执照图片 (最大 10MB, 仅支持 jpg/png)",
                        "name": "license",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回新的资质 URL",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/brand/profile": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "仅限品牌方(role=2) 调用。修改公司名、所属行业等参数。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "修改品牌方扩展资料",
                "parameters": [
                    {
                        "description": "品牌方资料参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateBrandProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功提示",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据当前 Token 获取用户的基本信息及对应角色的扩展资料（KOL或品牌方）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取账号详细信息",
                "responses": {
                    "200": {
                        "description": "成功返回用户信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/kol/profile": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "仅限 KOL(role=1) 调用。修改昵称、标签、底价等参数。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "修改 KOL 扩展资料",
                "parameters": [
                    {
                        "description": "KOL 资料参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.UpdateKOLProfileReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功提示",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/password/reset": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "验证旧密码并设置新密码。成功后将强制清除该用户在所有设备上的登录状态（全端踢下线）。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "修改登录密码",
                "parameters": [
                    {
                        "description": "修改密码参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.ResetPasswordReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\":0,\"message\":\"success\",\"data\":{\"message\":\"密码修改成功，请重新登录\"}}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/ugc/bind": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "绑定 B站/抖音/小红书 账号。支持 MVP 阶段不传 auth_token 自动从 Redis 读取。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UGC"
                ],
                "summary": "绑定第三方 UGC 账号 (受保护)",
                "parameters": [
                    {
                        "description": "绑定参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.BindUGCAccountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回绑定的平台和UID",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/user/ugc/bind/result": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "UGC"
                ],
                "summary": "手动/自动同步 UGC 最新数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "平台名称 (如 bilibili)",
                        "name": "platform",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "handlers.BindUGCAccountReq": {
            "type": "object",
            "properties": {
                "platform": {
                    "type": "string"
                },
                "platform_space_url": {
                    "type": "string"
                }
            }
        },
        "handlers.DeleteLicenseReq": {
            "type": "object",
            "properties": {
                "password": {
                    "description": "加上 vd 标签，防范前端传空字符串",
                    "type": "string"
                }
            }
        },
        "handlers.LoginReq": {
            "type": "object",
            "properties": {
                "account": {
                    "type": "string"
                },
                "client_type": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "description": "新增：前端需要告诉后端，用户是从哪个角色的专属页面发起的登录",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.RegisterReq": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "description": "手机号和邮箱字段 (可选加入正则校验)",
                    "type": "string"
                },
                "role": {
                    "$ref": "#/definitions/models.RoleType"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.ResetPasswordReq": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "handlers.UpdateBrandProfileReq": {
            "type": "object",
            "properties": {
                "company_name": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                }
            }
        },
        "handlers.UpdateKOLProfileReq": {
            "type": "object",
            "properties": {
                "base_quote": {
                    "description": "基础报价",
                    "type": "integer"
                },
                "real_name": {
                    "type": "string"
                },
                "tags": {
                    "description": "JSON字符串，如 \"[\\\"游戏\\\",\\\"主播\\\",\\\"知识\\\"]\"",
                    "type": "string"
                }
            }
        },
        "models.RoleType": {
            "type": "integer",
            "enum": [
                1,
                2,
                99
            ],
            "x-enum-varnames": [
                "RoleKOL",
                "RoleBrand",
                "RoleAdmin"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "KOL 营销平台用户中心 API",
	Description:      "User Center Microservice API Docs.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
