// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/match/brand/filter": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据所属行业、认证状态等维度筛选潜在合作的品牌方 (对标B站花火“找品牌”功能)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KOL匹配系统"
                ],
                "summary": "红人按条件筛选品牌方",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所属行业标签，如'数码'",
                        "name": "industry",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "是否已认证: 1-已认证, 0-未认证",
                        "name": "is_verified",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回品牌方列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.BrandFilterResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数解析失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Token无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "权限不足，仅限红人调用",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "系统检索异常",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/match/kol/filter": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据领域标签、粉丝量级、价格区间等多维度筛选红人列表 (对标B站花火“找红人”功能)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KOL匹配系统"
                ],
                "summary": "品牌方按标签筛选红人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "领域标签，如'美妆'",
                        "name": "field_tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "粉丝量级，格式'min,max'，如'10000,100000'",
                        "name": "fan_level",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最低报价限制",
                        "name": "price_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最高报价限制",
                        "name": "price_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回红人列表及总数",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.KolFilterResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数解析失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Token无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "权限不足，仅限品牌方调用",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "系统检索异常",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BrandFilterResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BrandSyncData"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.BrandSyncData": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "对应 brand_profiles.avatar_url",
                    "type": "string"
                },
                "brand_user_id": {
                    "description": "对应 sys_users.id",
                    "type": "integer"
                },
                "company_name": {
                    "type": "string"
                },
                "industry": {
                    "type": "string"
                },
                "is_verified": {
                    "description": "1-是 0-否",
                    "type": "integer"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.KolFilterResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.KolSyncData"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.KolSyncData": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "base_quote": {
                    "type": "number"
                },
                "credit_score": {
                    "type": "integer"
                },
                "fans_count": {
                    "type": "integer"
                },
                "platform": {
                    "type": "string"
                },
                "platform_uid": {
                    "type": "string"
                },
                "real_name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码 (非HTTP状态码，例如 0 表示成功，40001 表示参数错误)",
                    "type": "integer"
                },
                "data": {
                    "description": "实际的业务数据载荷 (如果没有数据，最好返回空结构体或 nil)"
                },
                "message": {
                    "description": "给前端展示或排查问题的提示语",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "匹配系统微服务 API (Match System Service)",
	Description:      "匹配系统接口文档，提供红人筛选、需求解析、受众重合度匹配等核心能力。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
