// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/kol/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "品牌方根据关键词、平台、领域标签、预算和粉丝数等条件动态筛选红人，支持分页和多种排序规则。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KOL匹配模块"
                ],
                "summary": "搜索红人列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词(匹配姓名/昵称)",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "description": "平台过滤，如 douyin, bilibili",
                        "name": "platforms",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "description": "领域标签过滤，如 数码, 美妆",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最小粉丝数",
                        "name": "min_fans",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最大粉丝数",
                        "name": "max_fans",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "最小报价预算",
                        "name": "min_price",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "最大报价预算",
                        "name": "max_price",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 (最小为1)",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "每页数量 (1-100)",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "credit_score",
                        "description": "排序字段：fans_count, base_quote, credit_score",
                        "name": "sort_by",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "desc",
                        "description": "排序方向：asc, desc",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回红人列表",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResponse-model_SearchKOLsResp"
                        }
                    },
                    "400": {
                        "description": "参数校验失败",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResponse-any"
                        }
                    },
                    "500": {
                        "description": "内部服务器错误",
                        "schema": {
                            "$ref": "#/definitions/model.BaseResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.BaseResponse-any": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {},
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.BaseResponse-model_SearchKOLsResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/model.SearchKOLsResp"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "model.KOLSearchResultVO": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "base_quote": {
                    "type": "number"
                },
                "credit_score": {
                    "type": "integer"
                },
                "fans_count": {
                    "type": "integer"
                },
                "platform": {
                    "type": "string"
                },
                "platform_uid": {
                    "type": "string"
                },
                "real_name": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "model.SearchKOLsResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.KOLSearchResultVO"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8002",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "匹配系统微服务 API (Match System Service)",
	Description:      "匹配系统接口文档，提供红人筛选、需求解析、受众重合度匹配等核心能力。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
