// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/match/brand/filter": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据所属行业、认证状态等维度筛选潜在合作的品牌方 (对标B站花火“找品牌”功能)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KOL匹配系统"
                ],
                "summary": "红人按条件筛选品牌方",
                "parameters": [
                    {
                        "type": "string",
                        "description": "所属行业标签，如'数码'",
                        "name": "field_tag",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "是否已认证: 1-已认证, 0-未认证",
                        "name": "is_verified",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回品牌方列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.BrandFilterResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数解析失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Token无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "权限不足，仅限红人调用",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "系统检索异常",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/match/im/history": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "传入目标用户ID(target_id)获取历史聊天记录。采用游标(cursor)分页机制解决深度分页性能问题及数据漂移问题；返回的数据已针对UI渲染做了倒序反转；并在后台异步清理未读红点。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IM消息模块"
                ],
                "summary": "获取指定会话的历史聊天记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标用户ID (被查询的KOL或品牌方UID)",
                        "name": "target_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "0",
                        "description": "分页游标：传入上一页返回的 next_cursor 字段值，首页传0即可",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "分页大小：防爆内存最大限制为100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功获取历史聊天记录及游标状态",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/im.HistoryMessagesResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数异常（如 target_id 缺失或非法）",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "未授权或Token失效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/match/im/sessions": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "提取当前登录用户的鉴权上下文，拉取其参与的所有IM会话列表。内置处理了目标用户的头像昵称聚合查询。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "IM消息模块"
                ],
                "summary": "获取当前用户的会话列表（左侧联系人列表）",
                "responses": {
                    "200": {
                        "description": "成功获取会话列表",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/im.SessionListResponseData"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "未授权或Token失效",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        },
        "/api/v1/match/kol/filter": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "根据领域标签、粉丝量级、价格区间等多维度筛选红人列表 (对标B站花火“找红人”功能)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KOL匹配系统"
                ],
                "summary": "品牌方按标签筛选红人",
                "parameters": [
                    {
                        "type": "string",
                        "description": "领域标签，如'美妆'",
                        "name": "field_tag",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "粉丝量级，格式'min,max'，如'10000,100000'",
                        "name": "fan_level",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最低报价限制",
                        "name": "price_min",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最高报价限制",
                        "name": "price_max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码，默认1",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页数量，默认20",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功返回红人列表及总数",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.KolFilterResp"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "参数解析失败",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "401": {
                        "description": "Token无效或已过期",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "403": {
                        "description": "权限不足，仅限品牌方调用",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    },
                    "500": {
                        "description": "系统检索异常",
                        "schema": {
                            "$ref": "#/definitions/response.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "db.IMMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "description": "强依赖此字段拉取历史消息",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "msg_id": {
                    "description": "极客提示：前端 JS 处理 64 位整型会丢失精度，因此 JSON 序列化时自动转为 string",
                    "type": "string",
                    "example": "0"
                },
                "msg_type": {
                    "type": "integer"
                },
                "receiver_id": {
                    "type": "integer"
                },
                "sender_id": {
                    "type": "integer"
                },
                "session_id": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "im.HistoryMessagesResponseData": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean",
                    "example": true
                },
                "messages": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/db.IMMessage"
                    }
                },
                "next_cursor": {
                    "type": "integer",
                    "example": 10086
                }
            }
        },
        "im.SessionItem": {
            "type": "object",
            "properties": {
                "latest_msg": {
                    "type": "string",
                    "example": "期待与您的合作！"
                },
                "session_id": {
                    "type": "string",
                    "example": "sess_123_456"
                },
                "target_avatar": {
                    "type": "string",
                    "example": "https://cdn.example.com/avatar.png"
                },
                "target_user_id": {
                    "type": "integer",
                    "example": 456
                },
                "target_user_name": {
                    "type": "string",
                    "example": "机智的何同学"
                },
                "unread_count": {
                    "type": "integer",
                    "example": 2
                },
                "updated_at": {
                    "type": "integer",
                    "example": 1672502400000
                }
            }
        },
        "im.SessionListResponseData": {
            "type": "object",
            "properties": {
                "sessions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/im.SessionItem"
                    }
                }
            }
        },
        "model.BrandFilterResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BrandSyncData"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.BrandSyncData": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "description": "对应 brand_profiles.avatar_url",
                    "type": "string"
                },
                "brand_user_id": {
                    "description": "对应 sys_users.id",
                    "type": "integer"
                },
                "company_name": {
                    "type": "string"
                },
                "is_verified": {
                    "description": "1-是 0-否",
                    "type": "integer"
                },
                "tags": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "model.KolFilterResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.KolSyncData"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.KolSyncData": {
            "type": "object",
            "properties": {
                "base_quote": {
                    "type": "number"
                },
                "kol_avatar_url": {
                    "type": "string"
                },
                "kol_user_id": {
                    "description": "对齐 kol_user_id",
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "total_followers": {
                    "type": "integer"
                },
                "ugc_accounts_detail": {
                    "description": "嵌套的账号详情数组",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UgcAccountDetail"
                    }
                },
                "ugc_platforms": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "description": "对齐 username",
                    "type": "string"
                }
            }
        },
        "model.UgcAccountDetail": {
            "type": "object",
            "properties": {
                "followers_count": {
                    "type": "integer"
                },
                "platform": {
                    "type": "string"
                },
                "platform_uid": {
                    "type": "string"
                }
            }
        },
        "response.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务状态码 (非HTTP状态码，例如 0 表示成功，40001 表示参数错误)",
                    "type": "integer"
                },
                "data": {
                    "description": "实际的业务数据载荷 (如果没有数据，最好返回空结构体或 nil)"
                },
                "message": {
                    "description": "给前端展示或排查问题的提示语",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "匹配系统微服务 API (Match System Service)",
	Description:      "匹配系统接口文档，提供红人筛选、需求解析、受众重合度匹配等核心能力。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
